/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package binaryconversor;

import java.util.ArrayList;
import java.util.stream.Collectors;

/**
 *
 * @author leoga
 */
public class Conversor extends javax.swing.JFrame {

    /**
     * Creates new form Conversor
     */
    public Conversor() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOperacoes = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        converter = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNumbit = new javax.swing.JTextField();
        converterbit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtNumHex = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        converterHex = new javax.swing.JButton();
        txtResultHex = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor Binário");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        txtResultado.setAutoscrolls(false);
        jScrollPane2.setViewportView(txtResultado);

        txtOperacoes.setEditable(false);
        txtOperacoes.setColumns(20);
        txtOperacoes.setRows(5);
        jScrollPane1.setViewportView(txtOperacoes);

        jLabel3.setText("Operações");

        jLabel2.setText("Resultado");

        jLabel1.setText("DECIMAL");

        converter.setText("converterParaBinario");
        converter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converterActionPerformed(evt);
            }
        });

        jLabel5.setText("BINARIO");

        converterbit.setText("converterParaDecimal");
        converterbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converterbitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumbit, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(converterbit, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(converter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel2)))
                .addGap(60, 60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(converter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(converterbit))
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("dec->binary", jPanel1);

        jLabel4.setText("numero");

        converterHex.setText("converter");
        converterHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converterHexActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Desculpe mas o conversor Hexadecimal \nainda não esta Pronto\n");
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNumHex, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(converterHex, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtResultHex))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumHex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(converterHex))
                .addGap(18, 18, 18)
                .addComponent(txtResultHex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("dec->hex", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("decimal->Binary");

        pack();
    }// </editor-fold>//GEN-END:initComponents
// so fiz este__________________________________________________________________
    private void converterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converterActionPerformed
            String numStr = txtNum.getText();
            double Num = Double.parseDouble(numStr);
            //listas------------------------------------------------------------
            ArrayList<Double> divisores = new ArrayList<>();
            ArrayList<Integer> binario = new ArrayList<>();
            
            for(double i = 1; i <= Num;i++){
                if (Num%i==0){
                    divisores.add(i);
                } 
            }
            //converte para binario---------------------------------------------
            double tempNum = Num;
            while (tempNum > 0){
                int sobra = (int)(tempNum % 2);
                binario.add(sobra);
                tempNum /=2;
            }
            //inverte os numeros para formar um binario-------------------------
            StringBuilder revBinarioStr = new StringBuilder();
            for (int i = binario.size() -1; i >= 0; i--){
                revBinarioStr.append(binario.get(i));
            }  
            //Lembrete
            //Exemplo numero 1812
            // - 1 e usado pois .size conta o tamanho do array a partir de 1
            // ele subtrai o valor a partir do index 11 até o 1 
            // mas o array começa a partir do index 0 e vai ate 10
            // no caso do numero 1812 a var binario retorna 00101000111 (x=nada)
            //  bits nao invertidos        = 0  0  1  0  1  0  0  0  1  1  1  x
            //                               ^  ^  ^  ^  ^  ^  ^  ^  ^  ^  ^  ^
            //index(local) no array        = 0  1  2  3  4  5  6  7  8  9  10 x
            //binario.size retorna         = x  1  2  3  4  5  6  7  8  9  10 11
            //                                  ^  ^  ^  ^  ^  ^  ^  ^  ^  ^
            //     sem subtrair ele para aqui-> 1  1  1  0  0  0  1  0  1  0  
            //         e como não existe index 11 no array ele começa aqui ^
            //se voce subitrai cada valor do binari.size por -1 ele fica assim
            //index(local) no array        = 0  1  2  3  4  5  6  7  8  9  10 
            //binario.size-1 retorna       = 0  1  2  3  4  5  6  7  8  9  10 
            //                               ^  ^  ^  ^  ^  ^  ^  ^  ^  ^  ^
            //bits nao invertidos          = 0  0  1  0  1  0  0  0  1  1  1
            //------------------------------------------------------------------
            //converte o array para string--------------------------------------
            String divisoresStr = String.join("-> ", 
                divisores.stream()
                        .map(Object::toString)
                            .toArray(String[]::new));
            
            String binarioStr = revBinarioStr.toString();
            if (binarioStr.contains("1")) {
                binarioStr = binarioStr.replaceFirst("^0+(?!$)", "");
            }
            
            
            
            //chama o BinarioStr e divisoresStr em suas respectivas textAreas
            //ou o output de sua escolha casa esteja usando fora do netbeans
            txtOperacoes.setText(divisoresStr);
            txtResultado.setText(binarioStr);
    }//GEN-LAST:event_converterActionPerformed

    private void converterHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converterHexActionPerformed
        //converção para HEXADECIMAL Ainda vai ser implementado
        String hexTable = "0123456789abcdef";
        String NumH = txtNumHex.getText();
    }//GEN-LAST:event_converterHexActionPerformed

    private void converterbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converterbitActionPerformed
        // input de sua escolha
        String binarioStr = txtNumbit.getText(); 
        // binario inteiro
        // int binario = Integer.parseInt(binarioStr);
        ArrayList<Integer> bits = new ArrayList<>();
        ArrayList<Integer> bitsInv = new ArrayList<>();
        ArrayList<Integer> tabela = new ArrayList<>();
        ArrayList<Integer> NumR = new ArrayList<>();
        for(int i=0;i < binarioStr.length(); i++){
            char digito = binarioStr.charAt(i);
            if (digito == '0'){
                bits.add(0);
            }else if(digito == '1'){
                bits.add(1);
            }else{
                txtOperacoes.setText("ERRO numero invalido digite somente 0 ou 1");
            }
        }
        for (int i=bits.size()-1;i >= 0; i--){
                int x = bits.get(i);
                bitsInv.add(x);
            }
        //define o tamanho da tabela decimal exp 1 4 8 16 32.....
        int NumAtual = 0;
        for(int i=0; i < bits.size();i++){
             if(NumAtual == 0){
                    NumAtual++;
                    tabela.add(NumAtual);
            }else if(NumAtual != 0){
                    NumAtual *=2;
                    tabela.add(NumAtual);
            }
        }               
        //seleciona os numeros correspondentes
        int x = 0;
        for(int i=0; i< tabela.size();i++){
            if (bitsInv.get(i)%2 != 0){
                x = tabela.get(i);
                NumR.add(x);
            }else{NumR.add(0);}
        }
        //soma 
        int resultado = 0;
        for(int i=0;i<NumR.size(); i++){
            resultado += NumR.get(i);
        }
         // output de sua escolha
        txtOperacoes.setText("bits: "+bits
                +"\n:bits em orden "+bitsInv+"\ntabela: "+tabela);
        txtResultado.setText("\nnumeros filtrados: "
                +NumR+"\nresultado: "+resultado);        
//binario                 1 1 1 0 0  0  1  0   1   0   0
//inverte o binario       0 0 1 0 1  0  0  0   1   1   1
//cria um array com o binario
//pega o tamnaho          1 2 3 4 5  6  7  8   9   10  11<-nao existe index 11
//todos os numeros-1      0 1 2 3 4  5  6  7   8   9   10<-começa do index certo
//binario                 0 0 1 0 1  0  0  0   1   1   1
//                        ^ ^ ^ ^ ^  ^  ^  ^   ^   ^   ^
//comparar multiplicaçoes 1,2,4,8,16,32,64,128,256,512,1024 multiplica 
//multiplica por binari.size  ^   ^            ^   ^   ^
//soma oque retornar par      4 + 16         + 256+512+1024 = 1812<-resultado
//Fim___________________________________________________________________________
    }//GEN-LAST:event_converterbitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversor().setVisible(true);
            }
        });
    }
//Fim___________________________________________________________________________
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton converter;
    private javax.swing.JButton converterHex;
    private javax.swing.JButton converterbit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtNumHex;
    private javax.swing.JTextField txtNumbit;
    private javax.swing.JTextArea txtOperacoes;
    private javax.swing.JTextField txtResultHex;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables


}
